# Site settings
name: devignite.in
title: DevIgnite
email: nikx.gupta@gmail.com
author: Nikhil Gupta
description:
url:

repository: 'nikx-gupta/nikx-gupta.github.io'

plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

markdown: kramdown
highlighter: rouge

